### ISSUE TITLE
Menu is directing Calibre to port 8010

### ISSUE THREAD

**Issue by floydianslips** [iiab/iiab-menu#4]
Calibre is installed on port 8080 but the config.json file directs Calibre to port 8010

**Comment by holta** [comment]
Workaround until this bug is fixed...

**Comment by holta** [comment]
Per @tim-moody's change 8 days ago, IIAB menuing uses Calibre port 8080 from [/opt/iiab/iiab-menu/config.json -> /library/www/html/iiab-menu/config.json](https://github.com/iiab/iiab-menu/blob/master/config.json#L6) (formerly 8010).

Reading variable "calibre_port:" from local_vars.yml might be an option in future, but is too complex at this point.
