### ISSUE TITLE
Menu won't load without Kiwix installation.

### ISSUE THREAD

**Issue by floydianslips** [iiab/iiab-menu#8]
If the Kiwix role isn't run common/assets/zim_version_idx.json isn't created. This leaves the menu hanging when accessed through the browser.

**Comment by tim-moody** [comment]
try it now

**Comment by holta** [comment]
@tim-moody's fix appears to be:

https://github.com/iiab/iiab-menu/commit/5671f84c0fa30986cce9ea5563966145d1ff4f63
